package util;

/**
 * Central configuration and protocol constants for the Multithreaded Chat Application.
 * <p>
 * Shared by both the server and client sides so that connection settings,
 * command keywords, and message formats are defined exactly once.
 * All members are immutable — this class holds no mutable global state.
 * </p>
 *
 * @author Sonu Singh
 * @version 1.0
 */
public final class Constants {

    // ------------------------------------------------------------------
    // Network configuration
    // ------------------------------------------------------------------

    /** Default host the client connects to. */
    public static final String DEFAULT_HOST = "localhost";

    /** Default TCP port the server listens on. */
    public static final int DEFAULT_PORT = 5000;

    /** Maximum time (ms) the client waits while attempting to connect. */
    public static final int CONNECT_TIMEOUT_MILLIS = 5_000;

    // ------------------------------------------------------------------
    // Chat commands (typed by the user in the client console)
    // ------------------------------------------------------------------

    /** Shows the list of available commands. */
    public static final String COMMAND_HELP = "/help";

    /** Lists all currently connected users. */
    public static final String COMMAND_LIST = "/list";

    /** Disconnects the client gracefully. */
    public static final String COMMAND_EXIT = "/exit";

    /** Clears the client console screen. */
    public static final String COMMAND_CLEAR = "/clear";

    // ------------------------------------------------------------------
    // Wire protocol markers (exchanged between server and client)
    // ------------------------------------------------------------------

    /** Server prompt asking the client for a username. */
    public static final String PROTOCOL_SUBMIT_USERNAME = "SUBMIT_USERNAME";

    /** Server response when the chosen username is already taken. */
    public static final String PROTOCOL_USERNAME_TAKEN = "USERNAME_TAKEN";

    /** Server response when the username was accepted. */
    public static final String PROTOCOL_USERNAME_ACCEPTED = "USERNAME_ACCEPTED";

    // ------------------------------------------------------------------
    // Display formatting
    // ------------------------------------------------------------------

    /** Timestamp pattern used for every chat message, e.g. "12:40 PM". */
    public static final String TIMESTAMP_PATTERN = "hh:mm a";

    /** Width of the console banner drawn on startup. */
    public static final int BANNER_WIDTH = 45;

    /** Character used to draw banner borders. */
    public static final char BANNER_BORDER_CHAR = '=';

    // ------------------------------------------------------------------
    // Server notifications
    // ------------------------------------------------------------------

    /** Message suffix broadcast when a user joins the chat. */
    public static final String NOTIFICATION_JOINED = " joined the chat";

    /** Message suffix broadcast when a user leaves the chat. */
    public static final String NOTIFICATION_LEFT = " left the chat";

    /** Name used for messages generated by the server itself. */
    public static final String SERVER_NAME = "SERVER";

    /**
     * Private constructor to prevent instantiation of this utility class.
     */
    private Constants() {
        throw new UnsupportedOperationException("Utility class cannot be instantiated.");
    }
}
